Develop/revise
masatotezuka/Login-function-express pull request #8
Opened 2022-03-02 06:32 UTC by masatotezuka

2022-03-03 09:01 UTC, kanamaru15 requested changes
@masatotezuka 指摘しました！

2022-03-03 09:01 UTC, kanamaru15 commented on routes/login.js
>  const middleware = require("../middleware");
@masatotezuka 
今回の対応箇所でないですが、気になった点を指摘します。
middlewareの定義を見ましたが、nodeでいうmiddlewareの使い方になってないです。
この辺は勘違いしていると、大変になるので、一度整理してください。
こちらとか参考になるかもです。
https://gist.github.com/mitsuruog/fc48397a8e80f051a145

現状の利用の仕方では、middleware.jsに定義されているものは、utility.js（便利な関数を定義）とかの役割かなと。
ただ、usersに関する責務であったり、するので、utilityとかでまとめるのは怪しい。
なので、まずは、middleware.jsの命名を変更してください。
node.jsのmiddlewareを意図して利用する場合は、middlewareフォルダを作り、どんな責務のmiddlewareなのかわかるファイル名とかにしてください。

2022-03-03 09:01 UTC, kanamaru15 commented on config/config.json
> +    "password": "tezukamasato1370",
@masatotezuka オープンリポジトリなので、パスワードは、個人に紐付きそうなものはやめた方が良いです。
なんでも良くても。

2022-03-03 09:01 UTC, kanamaru15 commented on models/index.js
> +'use strict';
@masatotezuka 
質問です。
これはなんで必要です？

2022-03-03 09:01 UTC, kanamaru15 commented on models/index.js
> +'use strict';
@masatotezuka このファイルが何をしているか、レビュー時に説明してください。

2022-03-03 09:01 UTC, kanamaru15 commented on models/user.js
> +  class User extends Model {
@masatotezuka これは何をしているか、説明できますか？
レビュー時に教えてください。

2022-03-03 09:01 UTC, kanamaru15 commented on routes/signup.js
> +    console.log(newuserFromdbusers);
@masatotezuka console.logはデバックとかで必要に応じて入れるのは良いですが、コミット時は消してください。
サーバーログを残すのであれば、必要なライブラリーを使ってください。

2022-03-03 09:01 UTC, kanamaru15 commented on routes/users.js
> +const User = require("../models").User;
@masatotezuka 
下記で良いのでは？
他のところでちゃんと記述ができていたので、どういう記述かレビュー時に説明してください。
const { User } = require("../models");

2022-03-03 09:01 UTC, kanamaru15 commented on routes/users.js
> +    console.log(error);
@masatotezuka 
ここで、エラーをキャッチすると、失敗時に何が起こったがわからなくなりますが大丈夫ですか？

2022-03-03 09:01 UTC, kanamaru15 commented on routes/users.js
> +    console.log(error);
@masatotezuka 
ここで、エラーをキャッチすると、失敗時に何が起こったがわからなくなりますが大丈夫ですか？

2022-03-03 11:30 UTC, masatotezuka commented on routes/login.js
>  const middleware = require("../middleware");
@kanamaru15 
記事の共有ありがとうございます！
記事を読みましたが、ユースケースがいまいちイメージがつかないです、、
ユーザーのセッション情報を確認するときに使いますか？

2022-03-04 00:54 UTC, masatotezuka commented on models/index.js
> +'use strict';
@kanamaru15 
Strictモードを意味していて、安全性が低い構文や非推奨の構文を使われていたらエラーを出してくれるものです。

2022-03-04 02:13 UTC, masatotezuka commented on models/user.js
> +  class User extends Model {
@kanamaru15 
[クラスModel](http://sequelize.org/master/class/src/model.js~Model.html)を継承してクラスUserを定義しているという認識です。。

2022-03-04 02:14 UTC, masatotezuka commented on routes/signup.js
> +    console.log(newuserFromdbusers);
了解しました！

2022-03-04 02:47 UTC, masatotezuka commented on routes/users.js
> +const User = require("../models").User;
理解が少しあいまいのまま使用していましたが、models/index.jsでdbのプロパティにUserを格納しているかと思います。
なので、models/index.jsでexportしているdbの中の「User」を読み込んでいる認識です。

2022-03-04 03:16 UTC, masatotezuka commented on routes/users.js
> +    console.log(error);
@kanamaru15 
`res.status(500).send(error);`に変更しました。

2022-03-04 03:16 UTC, masatotezuka commented on routes/users.js
> +    console.log(error);
@kanamaru15 
`res.status(500).send(error);`に変更しました。

2022-03-04 05:11 UTC, masatotezuka commented on config/config.json
> +    "password": "tezukamasato1370",
了解しました。nullにしました。

2022-03-05 15:27 UTC, masatotezuka commented
@kanamaru15 
`Error: Invalid value { firstName: '手塚' }` というエラーが修正できました！

2022-03-06 08:56 UTC, masatotezuka commented on routes/login.js
>  const middleware = require("../middleware");
メインの処理をするまえに、
`function(req, res, next) {
  // middlewareの処理
  next();
}`
ミドルウェア

2022-03-07 09:12 UTC, masatotezuka commented on routes/login.js
>  const middleware = require("../middleware");
こちらはだいぶイメージわきました！

2022-03-11 12:51 UTC, merged